- lib/onebox/engine.rb
- lib/onebox/engine/google_calendar_onebox.rb
I was added google calendar engine to be able to use in onebox by default.
https://meta.discourse.org/t/embed-google-calendar-plugin/21672/5?u=daniel_fernandez_pes
> added google calendar oneboxing

- lib/onebox/engine.rb
- lib/onebox/engine/github_commit_onebox.rb
- templates/githubcommit.mustache
should fix https://meta.discourse.org/t/22396
> [github_commit] Extract the first line of a commit as the title

- lib/onebox/engine/standard_embed.rb
- lib/onebox/helpers.rb
Reported [here](https://meta.discourse.org/t/vimeo-doesnt-work-on-1-2-0-beta6/24876?u=techapj)
> FIX: vimeo embed was broken

- lib/onebox/engine/whitelisted_generic_onebox.rb
> Whitelist Arstechnica

- lib/onebox/engine/github_commit_onebox.rb
- lib/onebox/engine/github_issue_onebox.rb
- lib/onebox/engine/github_pullrequest_onebox.rb
- lib/onebox/version.rb
- templates/githubcommit.mustache
- templates/githubissue.mustache
- templates/githubpullrequest.mustache
Requested here: https://meta.discourse.org/t/would-be-nice-to-see-repository-name-in-github-onebox/9708?u=techapj
Example:
> Include GitHub repo link for commit/PR/issue

- lib/onebox/engine/github_blob_onebox.rb
- lib/onebox/version.rb
- templates/githubblob.mustache
[Bug report here](https://meta.discourse.org/t/fa-spin-version-4/26801?u=techapj)
> FIX: fa-spin

- lib/onebox/engine/whitelisted_generic_onebox.rb
Please see: https://meta.discourse.org/t/very-large-gifs-should-be-shown-as-previews/25423/24?u=techapj
> Remove gfycat from whitelist

- lib/onebox/engine/whitelisted_generic_onebox.rb
> FEATURE: whitelist imdb.com

- lib/onebox/engine/google_maps_onebox.rb
- spec/lib/onebox/engine/google_maps_onebox_spec.rb
See https://meta.discourse.org/t/can-google-maps-be-embedded-into-topics/11146/54?u=elberet
> Google maps engine cleanup, support streetview maps

- lib/onebox/engine/amazon_onebox.rb
- spec/fixtures/amazon.response
- spec/lib/onebox/engine/amazon_onebox_spec.rb
- spec/lib/onebox/preview_spec.rb
- templates/amazon.mustache
Fix: https://meta.discourse.org/t/amazon-onebox-issue/29066
> FIX: Amazon onebox not working.

- lib/onebox/engine/steam_store_widget_onebox.rb
- spec/lib/onebox/engine/steam_store_widget_onebox_spec.rb
I didn't realize the composer would request the iframe at every keypress, so added a simple preview box and a spec for it.
> Addition of a placeholder_html preview box as an optimization

- lib/onebox/engine/google_calendar_onebox.rb
- lib/onebox/engine/google_docs_onebox.rb
- lib/onebox/engine/google_maps_onebox.rb
And calendar, too.
http://setup.googleapps.com/Home/user-resources/google-icons-and-logos/guidelines-for-using-google-brand-features
https://github.com/discourse/discourse/issues/3807
> FEATURE: Add placeholder for google docs oneboxes

- lib/onebox/engine/youku_onebox.rb
- spec/lib/onebox/engine/youku_onebox_spec.rb
Thanks @zh99998 for investigation.
Related (Chinese): https://meta.discoursecn.org/t/优酷、AcFun、bilibili-的-HTTPS-播放器/958
> FIX: https support for youku onebox

- lib/onebox/engine/whitelisted_generic_onebox.rb
Full thread at https://meta.discourse.org/t/consider-it-integration-in-discourse/44303
> Adding consider.it to onebox whitelist

- templates/_layout.mustache
- templates/amazon.mustache
- templates/douban.mustache
- templates/twitterstatus.mustache
- templates/whitelistedgeneric.mustache
- templates/wikipedia.mustache
strong element is not being closed at the end
> Update amazon.mustache to close strong element and generic template link to launch in separate window

- lib/onebox/engine/audio_onebox.rb
Adds m4a to list of file extensions.
> FEATURE: add m4a to audio onebox filetypes

- lib/onebox/engine/twitter_status_onebox.rb
- spec/fixtures/twitterstatus.response
- spec/lib/onebox/engine/twitter_status_onebox_spec.rb
the onebox couldn't be cached because of wrongly parsed timestamps
this fixes the error: `no _dump_data is defined for class Nokogiri::XML::Attr`
this is the alt. to #323
> [READY] fix bug in twitter onebox

- lib/onebox/helpers.rb
As per the below bug discussion now I fixed it
https://meta.discourse.org/t/500px-onebox-not-rendering-properly/58178?u=vinothkannans
> fix: normalizing % symbol in url gives broken URL

- lib/onebox/sanitize_config.rb
This is a pre-emptive measure: there is not an actual vulnerability that I am aware of.
1. Add a sandbox to all `<iframe>`s. The sandbox is very permissive, but still better than no sandbox.
2. Add `rel="noopener nofollow"`, the former is to prevent a certain kind of phishing attacks, and the latter discourage spammers.
Also, removed the excessive `merge` calls. `Sanitize::Config.merge` is a deep merge already.
> Security: sandbox iframes, add rel="noopener nofollow" to absolute anchors

- lib/onebox/sanitize_config.rb
> Sanitizer: Add iframe allow-presentation

- lib/onebox/engine/standard_embed.rb
- spec/fixtures/imdb.response
- spec/fixtures/imdb_mobile.response
- spec/lib/onebox/engine/whitelisted_generic_onebox_spec.rb
- spec/lib/onebox/engine/youtube_onebox_spec.rb
https://meta.discourse.org/t/imdb-embeds-broken-on-other-sites/35317/38?u=techapj
> FEATURE: prefer canonical link

- README.md
> Fixed headers in README.

- .rubocop.yml
- .travis.yml
- lib/onebox/engine/standard_embed.rb
- lib/onebox/helpers.rb
Build was failing for at least the first fix. 
- AllCops/Excludes &AllCops/Includes is now AllCops/Exclude and AllCops/Includes
- Correct linting issues
> Fix linting issues and make the build pass

- lib/onebox/engine.rb
- spec/lib/onebox/engine_spec.rb
https://meta.discourse.org/t/onebox-incorrectly-encodes-urls/61542/
> FIX: allow '&' in url

- .rubocop.yml
- .travis.yml
(this is failing, but only because master is failing. The good news is it's failing a lot **faster** than master is 😄  )
> Cache bundler for faster travis

- lib/onebox/engine/cloudapp_onebox.rb
- lib/onebox/engine/five_hundred_px_onebox.rb
- lib/onebox/engine/giphy_onebox.rb
- lib/onebox/engine/image_onebox.rb
- lib/onebox/engine/imgur_onebox.rb
- lib/onebox/engine/opengraph_image.rb
- lib/onebox/engine/whitelisted_generic_onebox.rb
I need 'onebox' css class to find and extract onebox images. Related to the topic https://meta.discourse.org/t/google-photos-images-not-downloaded/92068
> Add CSS class to image tag only oneboxes

- README.md
I may be wrong but I think it should be fixed this way.
> "its" possessive: not "it is"

- README.md
- lib/onebox.rb
- lib/onebox/engine.rb
- lib/onebox/engine/google_maps_onebox.rb
- lib/onebox/engine/reddit_image_onebox.rb
- lib/onebox/engine/youtube_onebox.rb
- lib/onebox/layout.rb
- lib/onebox/layout_support.rb
- lib/onebox/mixins/git_blob_onebox.rb
- lib/onebox/preview.rb
- onebox.gemspec
- spec/lib/onebox/engine/html_spec.rb
- spec/lib/onebox/engine/json_spec.rb
- spec/lib/onebox/engine_spec.rb
- spec/lib/onebox/layout_spec.rb
- spec/lib/onebox_spec.rb
- spec/spec_helper.rb
https://meta.discourse.org/t/google-maps-onebox-data-is-not-cached/59124/9
> Remove native caching.

- lib/onebox/engine/amazon_onebox.rb
- lib/onebox/engine/cloudapp_onebox.rb
- lib/onebox/engine/github_blob_onebox.rb
- lib/onebox/engine/gitlab_blob_onebox.rb
- lib/onebox/helpers.rb
- onebox.gemspec
> DEV: Update Rubocop and fix found issues

- lib/onebox/sanitize_config.rb
- lib/onebox/version.rb
Same as video, this allows for nofullscreen, nodownload etc.
> FIX: Allow controlslist attribute for audio

- .github/workflows/ci.yml
- lib/onebox/version.rb
- onebox.gemspec
* Use ruby/setup-ruby (w/ bundler caching)
* Use actions/checkout@v2
* Update ruby list (drop 2.4, add 2.7 and 3.0)
> DEV: Update GitHub Actons CI workflow

- lib/onebox.rb
- lib/onebox/engine/audio_onebox.rb
- lib/onebox/engine/video_onebox.rb
- spec/lib/onebox/engine/audio_onebox_spec.rb
- spec/lib/onebox/engine/video_onebox_spec.rb
This will add controlslist=nodownload to video and audio HTML players in the Video and Audio engines.
> FEATURE: Add disable_media_download_controls option

- lib/onebox/engine/github_commit_onebox.rb
- lib/onebox/version.rb
- templates/github/github_body.mustache
- templates/githubcommit.mustache
- templates/githubissue.mustache
- templates/githubpullrequest.mustache
Note that this commit also applies new github's body to commits.
> UX: makes github body full width

- lib/onebox/engine/google_docs_onebox.rb
> DEV: Make GoogleDocsOnebox use StandardEmbed
