- lib/onebox/engine/github_issue_onebox.rb
- templates/githubissue.mustache
See #264, removes the status (open/closed) text on Github Issues as there is no way to update this status.
> Remove Status tags/indications on GH issues

- lib/onebox/engine/classic_google_maps_onebox.rb
- spec/lib/onebox/engine/classic_google_maps_onebox_spec.rb
See discussion at [Discourse meta](https://meta.discourse.org/t/can-google-maps-be-embedded-into-topics/11146/32?u=elberet).
URLs of the form `https://www.google.de/maps/...` are converted iframe-embeddable URLs by looking up canonical URL and removing `&output=classic` from query parameters.
> Add support for Google Maps with www.google URLs

- lib/onebox/engine/whitelisted_generic_onebox.rb
So gfycat.com links will embed the mp4 and/or gif properly.
> Add gfycat.com to default whitelist

- lib/onebox/engine/classic_google_maps_onebox.rb
[Meta topic](https://meta.discourse.org/t/disable-map-scroll-by-default/26623?u=techapj).
Uses [this solution](http://stackoverflow.com/a/22567753) to disable scroll on map by default. Clicking anywhere on map will enable scroll again.
> FIX: disable google map scroll by default

- lib/onebox/engine/whitelisted_generic_onebox.rb
The `og:type` for `https://www.flickr.com/photos/steevithak` is `flickr_photos:photostream`, so the current code is detecting the URL as image type, instead of user profile.
Example:
> FIX: flickr user profile

- lib/onebox/engine/standard_embed.rb
- lib/onebox/engine/whitelisted_generic_onebox.rb
> Add gfycat handler

- lib/onebox/engine/standard_embed.rb
[Issue reported here.](https://meta.discourse.org/t/oneboxing-a-kickstarter-page-with-a-video-shows-just-the-video/21473/5?u=techapj)
Example:
> FIX: use oEmbed for kickstarter

- lib/onebox/engine/standard_embed.rb
> FIX: embedding ted talks was broken

- templates/twitterstatus.mustache
This will allow a css rule to set `white-space: pre-wrap;` on just the tweet text, displaying it correctly.
> Put tweet body in a tag of its own.

- lib/onebox/engine/standard_embed.rb
Vimeo videos that are embeddable but hidden from Vimeos search do not contain
an oembed url, despite this being available. The endpoint is taken from iframely:
https://github.com/itteco/iframely/blob/master/lib/plugins/system/oembed/providers.json#L42
> FIX: allow hidden but embeddable vimeo videos to display preview

- lib/onebox/engine/youtube_onebox.rb
- onebox.gemspec
Reported here: https://meta.discourse.org/t/embedded-youtube-videos-url-always-showing-https-youtube-com-devicesupport/28415?u=techapj
Also merge: https://github.com/discourse/discourse/pull/3437
> FIX: fetch YouTube video title via oEmbed

- lib/onebox/layout.rb
- lib/onebox/template_support.rb
- lib/onebox/view.rb
While trying to load custom templates I found that trying to load anything other than a custom `_layout` was not working, this is because right now the `View`s `template_path` is being set at require time, which is before custom paths are added. I noticed that there was already a nice way to handle falling back to the default templates in `Layout` so I just moved that out into a module and reused it here.
I hope this approach is OK, if you have a better idea please do let me know.
> allow custom load paths for templates other than _layout

- lib/onebox.rb
- lib/onebox/status_check.rb
- spec/lib/onebox/status_check_spec.rb
It returns a `Onebox::StatusCheck` instance that exposes the methods
`human_status` and `ok?`, wherein `human_status` returns symbols like
`:success` and `ok?` returns true if and only if the HTTP status code
lies between 200 and 299.
The status symbols follow the broad Rails terminology for status ranges (see <http://teamco-anthill.blogspot.co.uk/2010/04/rails-http-status-code-to-symbol.html>), so that would be:
- `:success` for 200-299
- `:client_error` for 400-499
- `:server_error` for 500-599
- `:unknown_error` for all other HTTP status codes
- `:connection_error` on timeouts, socket issues, etc
> Adding Onebox#check method, solving #154

- README.md
While developing a page which should be oneboxed, I found there were several undocumented rules around how the generic onebox will work beyond just whitelisting. I'm sure there are more, but these are what I encountered so far. I had to pick through the code and use the gem from IRB to figure these out.
FWIW, I'm not saying any of these things are bad or wrong they're just undocumented. It doesn't help that Discourse just responds `404` for everything with no indication of why it wasn't oneboxed.
> Update readme to include generic onebox caveats

- lib/onebox/engine.rb
- lib/onebox/engine/amazon_onebox.rb
- lib/onebox/engine/audio_onebox.rb
- lib/onebox/engine/github_blob_onebox.rb
- lib/onebox/engine/github_commit_onebox.rb
- lib/onebox/engine/github_gist_onebox.rb
- lib/onebox/engine/github_issue_onebox.rb
- lib/onebox/engine/github_pullrequest_onebox.rb
- lib/onebox/engine/google_calendar_onebox.rb
- lib/onebox/engine/google_docs_onebox.rb
- lib/onebox/engine/google_maps_onebox.rb
- lib/onebox/engine/google_play_app_onebox.rb
- lib/onebox/engine/image_onebox.rb
- lib/onebox/engine/pubmed_onebox.rb
- lib/onebox/engine/soundcloud_onebox.rb
- lib/onebox/engine/stack_exchange_onebox.rb
- lib/onebox/engine/standard_embed.rb
- lib/onebox/engine/twitter_status_onebox.rb
- lib/onebox/engine/video_onebox.rb
- lib/onebox/engine/whitelisted_generic_onebox.rb
- lib/onebox/engine/wikipedia_onebox.rb
- lib/onebox/engine/youtube_onebox.rb
- spec/lib/onebox/engine/stack_exchange_onebox_spec.rb
- spec/lib/onebox/engine/whitelisted_generic_onebox_spec.rb
- spec/lib/onebox/engine/wikipedia_onebox_spec.rb
- spec/lib/onebox/engine/youtube_onebox_spec.rb
- spec/lib/onebox/engine_spec.rb
This fixes mixed-content warnings for i.imgur.com and YouTube thumbnails, and makes sure that all requests leaving the server for these websites are always https.
https://meta.discourse.org/t/storing-images-in-the-cloud/6779/5
Also fixes that & was not being escaped in `link`
> Add "always https" declarations

- lib/onebox/engine/google_calendar_onebox.rb
Google now seems to be using calendar.google.com (at least in some cases) when they generate embed links for calendars.  This change allows either www.google.com (which was already being matched), or calendar.google.com as the host.
> Updated google calendar url regex to match calendar.google.com

- lib/onebox/engine/whitelisted_generic_onebox.rb
This PR adds the Australian Broadcasting Corporation News website to the whitelist for the `WhitelistedGenericOnebox`, making ABC News articles, The Drum opinion pieces, etc. nicely preview with Onebox.
> Add abc.net.au to whitelist.

- lib/onebox/engine/amazon_onebox.rb
- spec/spec_helper.rb
`Nokogiri::XML::Attr` cannot be serialized, so `image` must return a string for compatibility with caches that require serialization.
> Fix Amazon onebox data serialization

- onebox.gemspec
[Semver](http://semver.org/) means MINOR updates do not introduce backwards incompatibilities, so we should not lock MINOR.
> Do not lock MINOR in runtime deps

- lib/onebox/engine/twitter_status_onebox.rb
Video/photo links do not need to be treated differently from standard links, since all photo/video links have their "canonical URL" set to the the raw "status" URL, so all we need to do is match them to the existing onebox.
> Allow optional trailing slash on twitter URLs, and add support for video/photo URLs

- lib/onebox/engine/steam_store_onebox.rb
The Steam Store has changed their public URLs to include a description part after the app id. Unfortunately, anything included after the /widget iframe path now fails to resolve. This change takes the app id from the URL only and puts the widget/{app_id} part on.
Examples:
Old URL from Steam store page: http://store.steampowered.com/app/10
New URL (as of 25 April 2017): http://store.steampowered.com/app/10/CounterStrike/
Broken Widget path: http://store.steampowered.com/widget/10/CounterStrike/
Fixed Widget path: http://store.steampowered.com/widget/10
> Steam Store URL path update

- README.md
I guess this stopped working when GitHub switched to using this CommonMark parser:
- https://github.com/gjtorikian/commonmarker
> README: fix Markdown code blocks

- lib/onebox/web.rb
This commit should avoid the need to constantly reload the server in dev mode.
> FEATURE: use Sinatra::Reloader in development

- lib/onebox/layout.rb
- spec/lib/onebox/layout_spec.rb
We also might want to do
```ruby
@record[:image] =
"#{uri.scheme}://#{uri.host}/#{@record[:image][/(?!\/).*/]}"
```
To avoid getting
`https://us.battle.net//forums/static/images/social-thumbs/overwatch.png
` instead of
`https://us.battle.net/forums/static/images/social-thumbs/overwatch.png`
(watch for the double /)
It will work with `//` so I'm not fixing it for now.
> FIX: relative path mutation wasn’t used

- lib/onebox/engine/sketchfab_onebox.rb
Recent changes to the og:video tag on sketchfab allows us to pass several url parameters instead of just autostart.
For links that whose first parameter is not autostart, the previous code did nothing, causing the embed to autostart.
For links that have several parameters and start with autostart, the `?` is removed from the url, causing a 404.
This change removes only `autostart=1`, removing the autostart behavior and keeping all other behaviors as expected.
> Fixes sketchfab embeds

- lib/onebox/engine/gfycat_onebox.rb
- lib/onebox/sanitize_config.rb
- Title
- Favicon
- Author
- Tags
- Auto-plays on desktop
- Supports details gfycat URL
---
This will need a few lines off CSS in Discourse:
```diff
diff --git a/app/assets/stylesheets/common/base/onebox.scss b/app/assets/stylesheets/common/base/onebox.scss
index 61d92687fe..c692cfceb7 100644
--- a/app/assets/stylesheets/common/base/onebox.scss
+++ b/app/assets/stylesheets/common/base/onebox.scss
@@ -463,10 +463,22 @@ aside.onebox.stackexchange .onebox-body {
.label2 {
float: right;
}
-  .site-icon {
-    width: 16px;
-    height: 16px;
-    margin-right: 3px;
+}
+
+.onebox {
+  &.whitelistedgeneric,
+  &.gfycat {
+    .site-icon {
+      width: 16px;
+      height: 16px;
+      margin-right: 3px;
+    }
+  }
+}
+
+.onebox.gfycat p {
+  span.label1 a {
+    white-space: nowrap;
}
}
```
> New onebox for gfycat

- README.md
I'm reviewing the new engine instructions in the README since I hit some roadblocks just copying and pasting code from it. I think this changes will make life easier for future contributors.
I was trying to follow the new engine instructions and hit a bump at the curl fixture capture. The original version doesn't work on my machine (because it emits a `-GET` method and the server responds with `501 Method Not Supported`). I had to remove this dash to make it work.
Here is the version of curl I'm using: 
```
$ curl -V
curl 7.27.0 (i686-pc-linux-gnu) libcurl/7.27.0 OpenSSL/1.0.1c zlib/1.2.7 libidn/1.25 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB …
```
> Fix new engine instructions

- lib/onebox/engine/sketchfab_onebox.rb
Hey,
Lately we changed our 3d model page url scheme. It used to look like this `https://sketchfab.com/models/<id>` and now it can have one of the three following shapes:
- `https://sketchfab.com/models/<id>`
- `https://sketchfab.com/3d-models/<id>`
- `https://sketchfab.com/3d-models/<slug>-<id>`
I updated your regexp with the one we use internally @Sketchfab.
Cheers!
> Fix Sketchfab link regexp

- lib/onebox/engine/whitelisted_generic_onebox.rb
Currently we do not hit VimeoOnebox engine.
```ruby
Onebox.preview("https://vimeo.com/97765630").send(:engine).class
#Onebox::Engine::WhitelistedGenericOnebox
```
> FIX: use vimeo engine instead of whitelisting it

- lib/onebox/engine/github_blob_onebox.rb
- lib/onebox/mixins/git_blob_onebox.rb
- spec/lib/onebox/engine/github_blob_onebox_spec.rb
- templates/githubblob.mustache
Github has code for displaying stl files but the existing onebox engine would treat the file as text.
I modified the github_blob engine to put the "render.githubusercontent.com/view/solid" link in an iframe if the file type ends with stl.
You can test this using "https://github.com/nophead/Mendel90/blob/master/dibond/stls/x_motor_bracket.stl"
I've never written anything in ruby so be gentle. :)
> Update github_blob engine to support displaying stl files

- lib/onebox/engine.rb
- lib/onebox/helpers.rb
- spec/lib/onebox/engine_spec.rb
- spec/lib/onebox/helpers_spec.rb
Inspired from: https://github.com/puppetlabs/puppet/commit/49bfae4666714aa38aa1220d3762f8e926292645
> FIX: encode the URL per RFC 3986 spec

- lib/onebox/engine/whitelisted_generic_onebox.rb
We prefer to render our own video/image, rather than loading an iframe. For Facebook videos, the twitter card iframe contains an auto-playing video which is not user friendly. With this change, the facebook video will be displayed in a native `<video>` player, without autoplay.
> Deprioritize Twitter card in generic onebox

- lib/onebox/engine/typeform_onebox.rb
Dashes or underscores seem to be allowed by Typeform but did not trigger the mixin so far.
Adapting the regex already fixed the issue for our customer.
Refines #394 by @romanrizzi - Thank you for the good work on making Typeform supported again!
> Support more Typeform subdomains

- lib/onebox/engine/youtube_onebox.rb
Added the ability to pass in the param enablejsapi. This is needed for tracking within Tag Manager.
https://developers.google.com/youtube/player_parameters#enablejsapi
> Added enablejsapi param

- lib/onebox/engine/google_maps_onebox.rb
This method, `follow_redirect!` is being called on urls that do not need to redirect, and return 200 status. If that is the case, just return the uri!
> FIX: Follow redirect returns url if response code is 200

- lib/onebox/engine/gfycat_onebox.rb
Trying to fix this issue in email where the gfycat preview image float isn't cleared and extends outside the container...
> Fix for gfycat onebox in email

- lib/onebox/helpers.rb
- spec/lib/onebox/helpers_spec.rb
Since #418 introduced the `addressable` gem as a runtime dependency, it's now possible to replace all custom URI encoding logic with addressable's methods.
~~This change is non-breaking, at least as far as the tests go, but it is possible that some characters (that aren't covered by specs) are now escaped and they weren't before (or the other way around).~~
It does handle some characters differently - e.g. it now doesn't escape URLs in URI fragments (see the added test). Previous escaping behavior was reported as an issue in Discourse.
> DEV: Replace custom uri_encode logic with Addressable

- .github/workflows/ci.yml
Whenever a new tag (e.g. `v1.9.26`) is pushed and the tests pass, the workflow will automatically create a new release on rubygems.
> DEV: Publish to rubygems on tag push

- lib/onebox/helpers.rb
- spec/lib/onebox/helpers_spec.rb
- spec/support/html_spec_helper.rb
FIX: Correctly parse relative redirects using Addressable
Also rename 'header' to 'redir_header' to deconflict with 'headers' parameter
---
We were slamming cookies together, such that the last parameter of one cookie would bleed into the name of the next. Medium.com was not happy with this arrangement.
> FIX: Fix handling of multi-cookie responses

- lib/onebox/engine.rb
- lib/onebox/engine/allowlisted_generic_onebox.rb
- lib/onebox/engine/bandcamp_onebox.rb
- lib/onebox/engine/facebook_media_onebox.rb
- lib/onebox/engine/google_calendar_onebox.rb
- lib/onebox/engine/google_maps_onebox.rb
- lib/onebox/engine/kaltura_onebox.rb
- lib/onebox/engine/sketchfab_onebox.rb
- lib/onebox/engine/slides_onebox.rb
- lib/onebox/engine/steam_store_onebox.rb
- lib/onebox/engine/trello_onebox.rb
- lib/onebox/engine/twitch_clips_onebox.rb
- lib/onebox/engine/typeform_onebox.rb
- lib/onebox/engine/vimeo_onebox.rb
- lib/onebox/engine/wistia_onebox.rb
- lib/onebox/engine/youku_onebox.rb
- lib/onebox/engine/youtube_onebox.rb
- lib/onebox/matcher.rb
- lib/onebox/mixins/twitch_onebox.rb
- lib/onebox/preview.rb
- lib/onebox/sanitize_config.rb
- lib/onebox/version.rb
- spec/lib/onebox/engine/twitch_clips_onebox_spec.rb
- spec/lib/onebox/engine/twitch_stream_onebox_spec.rb
- spec/lib/onebox/engine/twitch_video_onebox_spec.rb
- spec/lib/onebox/matcher_spec.rb
- spec/lib/onebox/preview_spec.rb
- spec/spec_helper.rb
All onebox engines now define their desired iframe domains using `requires_iframe_origins`
Consumers can choose to pass an array of `allowed_iframe_origins` in `options`. Engines which require iframe origins not included in the list will be skipped. The sanitizer will also strip all iframes which are not in the allowed list. If `allowed_iframe_origins` is unspecified, all required_iframe_origins will be allowed.
> FEATURE: Add more control of iframe embeds

- lib/onebox/engine/allowlisted_generic_onebox.rb
- lib/onebox/engine/instagram_onebox.rb
- lib/onebox/preview.rb
- onebox.gemspec
- spec/fixtures/instagram_alternative.response
- spec/lib/onebox/engine/instagram_onebox_spec.rb
The previous way of obtaining the image (appending `/media/?size=l` to the URL) has been deprecated. Update to use the image URL that is explicitly returned as part of the response payload.
**NOTE**: this image URL is timestamped and will only work for a limited period of time, so the image may need to be cached locally.
The previous author_name regex failed if the name contained a period character (`.`). Regex updated to allow for those.
Sometimes a description is returned in a different format. Handle those cases.
> FIX - New image URLs. Usernames with `.` characters. Different description formats.

- lib/onebox/engine/instagram_onebox.rb
Raise an error if no oembed.data is found (e.g., if you have an invalid token). This will make the onebox generation fail, and return an empty onebox. Discourse itself will fallback to using the original link if the onebox is empty.
> FIX: raise error if no data available to Instagram engine

- lib/onebox/engine/github_folder_onebox.rb
- spec/fixtures/githubfolder-discourse-root.response
- spec/lib/onebox/engine/github_folder_onebox_spec.rb
When linking to a subsection within a github repo’s README file that is displayed beneath a folder listing (e.g. `https://github.com/discourse/discourse#setting-up-discourse`), the engine should attempt to extract the title of the subsection from the HTML, and display that within the generated GithubFolderOnebox.
`matches_regexp` was also modified to allow github organization and repo names to have non-alpha characters
> FEATURE: Display section title when URL contains fragment 

- lib/onebox/engine/github_folder_onebox.rb
- lib/onebox/version.rb
- spec/lib/onebox/engine/github_folder_onebox_spec.rb
- templates/githubfolder.mustache
Always use the original URL, which will retain the fragment if it was originally present.
Previously, the original URL with fragment would only be included if you were deep linking to a non-root folder.
> FIX: Simplify how we link to github folders

- lib/onebox/engine/allowlisted_generic_onebox.rb
- lib/onebox/version.rb
- spec/lib/onebox/engine/allowlisted_generic_onebox_spec.rb
This commit prevents oneboxing of links that only has title in metadata.
> FIX: do not show title only oneboxes

- lib/onebox/engine/instagram_onebox.rb
- spec/lib/onebox/engine/instagram_onebox_spec.rb
Instagram TV (or ‘IGTV’) links should be processed by the Instagram Onebox Engine. This means the data will be fetched via Instagram’s official oEmbed endpoint and, if an access token is configured, will not be subject to login redirects, etc.
> FEATURE: support Instagram TV links

- lib/onebox/engine/github_issue_onebox.rb
- lib/onebox/engine/json.rb
- lib/onebox/engine/pubmed_onebox.rb
- lib/onebox/mixins/git_blob_onebox.rb
- lib/onebox/status_check.rb
Makes the gem compatible with Ruby 3.
> DEV: Call `URI.open` explicitly

- lib/onebox.rb
- lib/onebox/version.rb
Not needed as per comments in https://github.com/discourse/onebox/pull/454
> DEV: Remove default for disable_media_download_controls

- lib/onebox/engine/amazon_onebox.rb
- lib/onebox/version.rb
We use a custom user agent when making requests against various Amazon properties. However, the user agent is quite old which may be a cause of 503 errors that users are noticing when oneboxing Amazon URLs.
Updating this user agent to a current/more popular user agent may help avoid these errors.
> FIX: Update user agent used for Amazon requests

- lib/onebox/engine/allowlisted_generic_onebox.rb
- lib/onebox/helpers.rb
- lib/onebox/open_graph.rb
- spec/lib/onebox/helpers_spec.rb
Attempt to validate the format of URLs for image and video attributes, and remove any values that appear to be invalid.
> FIX: Validate format of links

- lib/onebox/engine/gfycat_onebox.rb
- lib/onebox/engine/google_docs_onebox.rb
- lib/onebox/engine/html.rb
- lib/onebox/engine/pastebin_onebox.rb
- lib/onebox/engine/twitter_status_onebox.rb
- lib/onebox/helpers.rb
- lib/onebox/version.rb
Optionally pass in a simple caching mechanism provider to `body_cacher` to allow for caching/fetching the bodies of successful HTTP GET requests.
The caching mechanism you provide should support methods called:
`fetch_cached_response_body`
`cached_response_body_exists?`
These methods expect a single argument of a URL string.
`cache_response_body`
Expects a URL string, and the response body string.
> FEATURE: Body cacher

- lib/onebox/engine/amazon_onebox.rb
- lib/onebox/version.rb
- spec/lib/onebox/engine/amazon_onebox_spec.rb
(**NOTE:** This builds upon https://github.com/discourse/onebox/pull/460)
- Add additional Amazon domains to support additional countries
- If available, grab the `canonical` URL for a given Amazon URL from a cache, rather than making a separate HTTP GET request.
- If the `canonical` URL can not be determined, we use a new shorter `/dp/` link, which seems to be preferred by Amazon at the moment.
- Allow the passing in of a custom user-agent to use on Amazon requests.
> DEV: updates to Amazon Oneboxing

- lib/onebox/engine/amazon_onebox.rb
- lib/onebox/engine/html.rb
- lib/onebox/version.rb
- spec/lib/onebox/engine/amazon_onebox_spec.rb
* Use the canonical URL as the link within the generated onebox
* Use the `data-old-hires` value for the image URL, if available
* Version bump to 2.2.10
> DEV: Small Amazon fixes

- lib/onebox/engine/github_issue_onebox.rb
- lib/onebox/engine/github_pullrequest_onebox.rb
- lib/onebox/mixins/github_body.rb
- lib/onebox/version.rb
- templates/github/github_body.mustache
- templates/githubissue.mustache
- templates/githubpullrequest.mustache
Note that this PR is also slightly changing github issues body position, and is using raw instead of text in the API call to get the raw body of the issue instead of a text only version.
This PR needs a companion PR in discourse core for the JS behavior: https://github.com/discourse/discourse/pull/12698
> UX: display long PRs/Issues in an expandable excerpt

- onebox.gemspec
See https://nvd.nist.gov/vuln/detail/CVE-2021-32740
Fixed in https://github.com/sporkmonger/addressable/commits/addressable-2.8.0
> Update addressable to address CVE-2021-32740
